name: Cypress Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge] # Specify browsers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0' # Use Node.js version 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Start application (background)
        run: cmd /c "start /B npm start"

      - name: Wait for application to be available
        shell: pwsh
        run: |
          while (!(Invoke-WebRequest -Uri http://localhost:3000 -UseBasicParsing -ErrorAction SilentlyContinue)) {
            Write-Host "Waiting for application to be available..."
            Start-Sleep -Seconds 5
          }
      

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }} # Use matrix value for browser
          record: true
          wait-on: "http://localhost:3000" # Ensure app is ready
          wait-on-timeout: 300 # Increased timeout to 300 seconds
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
