name: Cypress Tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge] # Specify the browsers you want to test
        # containers: [1, 2]  <- Remove or adjust if you still need parallel containers
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start # Or your start command
          # wait-on: "http://localhost:3000 --timeout 120000"
          record: true
          # parallel: true <- Remove or adjust if you still need parallel containers
          browser: ${{ matrix.browser }} # Use matrix value for browser
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}